version: '3.9'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432 # The default port for Postgres.

# Provides a web interface for database management.
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080